project:
  type: website

website:
  title: "Affordable Housing Analysis"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Housing vs Income"
        href: section2.html
      - text: "Housing vs POPS"
        href: section3.html
      - text: "K-Means Analysis"
        href: section4.html

execute: 
  enabled: true
  warning: false 
  error: false   

format:
  html:
    code-fold: true
    theme: cosmo
    css: styles.css
    toc: true

